### ISSUE TITLE
Simple way to print a tree

### ISSUE THREAD

**Issue by G3z** [vicklr/materialized-model#1]
I did not find a simple way to print the nodes in `tree` order:
```
root1 (p: / d:0)
-- child1 (p: /1 d:1)
---- grandchild1 (p: /1/2 d:2)
-- child2 (p: /1 d:1 d:1)
---- grandchild2 (p: /1/4/ d:2)
root2 (p: / d:0)
```
getting entries in order from the database is fundamental for pagination

**Comment by MithrandirDK** [comment]
Retrieving the nodes in a tree order is a quite difficult problem when you pull in pagination.

Without pagination, and loading the full tree, it could be done like this:
`SomeModel::get()
  ->toHierarchy()
  ->roots()
  ->each(fn(MaterializedModel $model) => print_self_and_children($model));

function print_self_and_children(MaterializedModel $model) {
    echo str_pad($model->title, '-', strlen($model->title) + $model->getDepth(), STR_PAD_LEFT);
    $model->children
        ->each(fn(MaterializedModel $model) => print_self_and_children($model));
}
`

But with pagination, it is really quite impossible to get only the entries that are actually "on that page" - what if the first element on page 2 is a child to the last element on page 1? How do we denote that?

Also, the ordering in the database would have to somehow "know" how to order recursively.

I do not know how I would solve this - in all my uses of hierarchies, if there are many items, I would load only one level at a time and make AJAX or similar calls to get only direct children when opening sub-items to a parent item.

I know this does not necessarily help you directly, but if you have a way that you would like it to function (on the database level), I may be able to do something, but as I see it, it would have to use a pre-calculated value for paginated ordering that would have to be re-calculated every time the tree changes (at least additions and moves).

**Comment by G3z** [comment]
I also think that to do what i asked we either need another column or use the ordering column in a global way. 
the problem, as you pointed out, is that every modification of the tree should update all subsequent nodes with an `update` query.
I need to build an admin table for my records, i guess I'be using another package. thanks anyway!
